### ISSUE TITLE
Feature request: Show a hint

### ISSUE THREAD

**Issue by vnijs** [rmotr/jupyterlab-solutions#1]
jupyterlab-solutions looks very nice! When I saw the option to see the solution I was wondering if it might be possible to also have an option for a "hint". I'm not sure if the extension offers the option to keep score as students work through the assignment but if so, the hint could possible lower the overall score a bit

**Comment by vnijs** [comment]
I haven't installed the extension yet. But will do so soon and report if there are any issues.

FYI I did something like this in R and shiny a few years back. Although basic, it has worked pretty well for us so far (https://github.com/vnijs/quizr). See https://vnijs.shinyapps.io/quizr/ to a simple example.

To add questions the instructor would call a function that generates the required (shiny) R code (see example below). When working through the assignments, students can then keep track of their answers and scores in the "Your answers" tab

```
make_quiz("1.01", "At what price would Iceskimo sell 75 cups?",
          paste0("$",c("2.00","2.50","3.00","3.50","4.00")),
          "$2.50", "At a price of $2.50 demand would be \\(100 - 10 \\times 2.50 = 75\\)",
          "In the equation above replace the 0 by 75 and solve for p")
```

**Comment by santiagobasulto** [comment]
Thanks for sharing, it's a good example. We're evaluating good ways to add grading. What does your extension accept as "answers"? Are always closed answers compared with the user's input, or is it possible to also check the code/output submitted by the student?

**Comment by vnijs** [comment]
Mine is just for multiple-choice questions. A bit closer to what you are doing, again in R, is the `learnr` package. 

https://rstudio.github.io/learnr/

**Comment by santiagobasulto** [comment]
@vnijs we have implemented this and it's now available on [notebook.ai](https://notebook.ai)!

**Comment by vnijs** [comment]
Great! Do you have a demo I can see? notbook.ai just points to their homepage

**Comment by santiagobasulto** [comment]
Yes! Check the "Exercises" notebook in this example: https://notebooks.ai/fork/rmotr-curriculum/interactive-jupyterlab-tutorial

**Comment by vnijs** [comment]
Nice. Does this also "check" for a correct answer? You might also be interested in the following excellent repos by @ines that are in a related space:

https://github.com/ines/spacy-course

https://github.com/ines/course-starter-python
