### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by michaeljgant** [rmotr/jupyterlab-solutions#3]
Followed the installation instructions but the "Mark as solution" button doesn't appear. Changing the cells metadata to 
```
{
    "cell_type": "solution"
} 
```
doesn't work either. And the example hosted on notebooks.ai is also not working

**Comment by michaeljgant** [comment]
Ok now it is working on notebook.ai for some reason. Will keep trying to get it working locally and update

**Comment by santiagobasulto** [comment]
Hey @michaeljgant! On [notebook.ai](https://notebook.ai) it works as I'm using it right now. Are you having an issue locally? I'll close this issue for now, let us know if it doesn't work.

**Comment by michaeljgant** [comment]
It's still not working.

I installed a fresh Ubuntu 18.04, updated packages, installed python 3.6, created a virtual environment, installed jupyterlab 0.35.4

Then I installed nodejs and npm

Then I installed 4 juypterlab extensions in the virtual environment, spellchecker, toc, juypter-lab-manager and juypter-lab-solutions.

Still in the venv I ran 
```
pip install jupyterlab-solutions
jupyter serverextension enable jupyterlab_rmotr_solutions
```
Finally I ran ` jupyter lab`, created a python 3 notebook and there was no "Mark as solution" button and changing the cells metadata didn't work either

**Comment by santiagobasulto** [comment]
Did you also follow these instructions? https://github.com/rmotr/jupyterlab-solutions#development

**Comment by michaeljgant** [comment]
No I didn't, will try them now

**Comment by michaeljgant** [comment]
No it still didn't work

**Comment by michaeljgant** [comment]
We were able to figure out why it wasn't working. We needed to change the  ~/.jupyter/jupyter_notebook_config.py file and set `c.JupyterLabRmotrSolutions.role = 'teacher' `
Then the mark as solution button appears and cells can be marked as solutions. Then we change the role back to student and the solution cells work
